#!/bin/sh

uci -q set luci.main.lang='zh_cn'
uci -q set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci -q set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

uci -q del network.lan
uci -q set network.lan='interface'
uci -q set network.lan.device='eth0'
uci -q set network.lan.proto='static'
uci -q set network.lan.ipaddr='10.0.0.5'
uci -q set network.lan.netmask='255.255.255.0'
uci -q set network.lan.gateway='10.0.0.1'
uci -q set network.lan.delegate='0'
uci -q add_list network.lan.dns='114.114.114.114'
uci -q del network.@device[0]
uci -q del network.globals.ula_prefix
uci commit network

uci -q set system.@system[0].zonename='Asia/Shanghai'
uci -q set system.@system[0].timezone='CST-8'
uci -q del system.ntp.server
uci -q add_list system.ntp.server='ntp.aliyun.com'
uci -q add_list system.ntp.server='0.openwrt.pool.ntp.org'
uci commit system

uci -q del wireless.default_radio0
uci commit wireless

if [[ $(uci -q show aria2 | wc -l)>0 ]]; then
  uci -q set aria2.main.enabled='1'
  uci -q set aria2.main.user='root'
  uci -q set aria2.main.dir='/mnt/mmcblk2p4/aria2'
  uci -q set aria2.main.check_certificate='false'
  uci -q del aria2.main.extra_settings
  uci commit aria2
fi

if [[ $(uci -q show transmission | wc -l)>0 ]]; then
  uci -q set transmission.@transmission[0].enabled='1'
  uci -q set transmission.@transmission[0].user='root'
  uci -q set transmission.@transmission[0].group='root' 
  uci -q set transmission.@transmission[0].download_dir='/mnt/mmcblk2p4/transmission'
  uci -q set transmission.@transmission[0].cache_size_mb='500'
  uci -q set transmission.@transmission[0].encryption='0'
  uci -q set transmission.@transmission[0].utp_enabled='false'
  uci -q set transmission.@transmission[0].dht_enabled='false'
  uci commit transmission
fi

if [[ $(uci -q show alist | wc -l)>0 ]]; then
  uci -q set alist.@alist[0].enabled='1'
  uci commit alist
fi

if [[ $(uci -q show filebrowser | wc -l)>0 ]]; then
  uci -q set filebrowser.config.enabled='1'
  uci commit filebrowser
fi

if [[ $(uci -q show turboacc | wc -l)>0 ]]; then
  uci -q set turboacc.config.sfe_flow='1'
  uci -q set turboacc.config.bbr_cca='1'
  uci -q del turboacc.config.sw_flow
  uci commit turboacc
fi

if [[ $(uci -q show AdGuardHome | wc -l)>0 ]]; then
  uci -q set AdGuardHome.AdGuardHome.enabled='1'
  uci commit AdGuardHome
  chmod 0700 /etc/AdGuardHome
  chmod 0700 /etc/AdGuardHome/data
fi

rm -rf /tmp/luci-*

# Disable opkg signature check
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
# Add environment variables
sed -i "15aexport TERM=xterm" /etc/profile